#!/usr/bin/env ruby
##
 # Deploys website files inside a bare repository
 # to default Apache location /var/www/{site name}
##
require 'time'
timestamp = Time.now.utc.iso8601

# read args from STDIN ("from_commit, to_commit, branch_name")
from, to, branch = ARGF.read.split " "

# only deploy master branch
if (branch =~ /master$/) == nil
    `cat '#{timestamp}\t\treceived non-master branch \'#{branch}\', not deploying\n' >> ../hook-post-receive.log`
    exit
end

# copy files to deploy directory
sitename = File.basename(File.expand_path("../", Dir.pwd))
dest_dir = File.expand_path("/var/www/#{sitename}")
`GIT_WORK_TREE="#{dest_dir}" git checkout -f master`
`cat '#{timestamp}\t\tdeployed master(at #{to}) to \'#{dest_dir}\'\n' >> ../hook-post-receive.log`

# TODO: rebuild Docker container
