#!/usr/bin/env zsh

# Configure macOS preferences
# inspired by https://github.com/paulirish/dotfiles

# Prevent startup when opening the lid or connecting to power
sudo nvram BootPreference=%00

# ---
# Dock preferences

defaults write com.apple.dock "autohide" -bool "true"
defaults write com.apple.dock "autohide-time-modifier" -float "0"
defaults write com.apple.dock "show-recents" -bool "false" 
defaults write com.apple.dock "tilesize" -int "69"
defaults write com.apple.dock "mru-spaces" -bool "false"
defaults write com.apple.dock "expose-group-apps" -bool true

# ---
# Finder preferences

# Show all filename extensions
defaults write com.apple.finder "AppleShowAllFiles" -bool "true"
defaults write com.apple.finder "ShowPathbar" -bool "true"
defaults write com.apple.finder "FXPreferredViewStyle" -string "clmv"
defaults write com.apple.finder "FXEnableExtensionChangeWarning" -bool "false"
defaults write com.apple.finder "WarnOnEmptyTrash" -float "0"
# Default save directory
defaults write NSGlobalDomain "NSDocumentSaveNewDocumentsToCloud" -bool "false" 
# Show the ~/Library folder
chflags nohidden ~/Library
# Show the /Volumes folder
sudo chflags nohidden /Volumes
# Set the ~/Downloads folder to group by date
# set_downloads_sort_script="/Users/peter/scripts/applescript/set_downloads_sort.scpt"
# [[ -f "$set_downloads_sort_script" ]] && osascript "$set_downloads_sort_script"

# ---
# Scrolling, Trackpad, and Keyboard preferences

# Disable “natural” (Lion-style) scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool "false"
# Remove the default Spotlight shortcut Command + Space
# defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 64 "<dict><key>enabled</key><false/></dict>"
# Speed up key repeat rate
defaults write NSGlobalDomain "KeyRepeat" -int "2"
# short delay until key repeat
defaults write NSGlobalDomain "InitialKeyRepeat" -int "20"
# Map Caps Lock key to Escape function
# FIXME
# hidutil property --set '{\"UserKeyMapping\":[{\"HIDKeyboardModifierMappingSrc\":0x700000039,\"HIDKeyboardModifierMappingDst\":0x700000029}]}'
# enable key repeat for press and hold
defaults write NSGlobalDomain "ApplePressAndHoldEnabled" -bool "false"
# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain "AppleKeyboardUIMode" -int "3"
# Enable tap to click for the trackpad
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# ---
# Hot corners
#
# corner values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 
# modifier values:
# 1048576: Command

# Top left
defaults write com.apple.dock wvous-bl-corner -int 0
defaults write com.apple.dock wvous-bl-modifier -int 0
# Top right
defaults write com.apple.dock wvous-tr-corner -int 12
defaults write com.apple.dock wvous-tr-modifier -int 1048576
# Bottom left
defaults write com.apple.dock wvous-tl-corner -int 10
defaults write com.apple.dock wvous-tl-modifier -int 1048576
# Bottom right
defaults write com.apple.dock wvous-br-corner -int 4
defaults write com.apple.dock wvous-br-modifier -int 1048576

