#!/bin/bash
#
# Setup symlinks for dotfiles
#
# USAGE
#	$ setup-dotfiles /path/to/dotfiles
#

DOTFILES="$1"
[ -z "$DOTFILES" ] && echo -e "Error: Missing argument\nUsage:\n\t$ setup-dotfiles /path/to/dotfiles" && exit 1
[ ! -d "$DOTFILES" ] && echo "Error: dotfiles directory \"$DOTFILES\" does not exist." && exit 1

setup_symlink() {
    SRC=$1;
    DEST=$2;
    if [ -e $DEST ]; then
        echo "$DEST already exists, skipping it. Delete the file and re-run script to setup symlink."
        return 1;
    fi
    ln -s "$SRC" "$DEST" && echo "Symlink created for $DEST."
}

echo -e "Creating symlinks for dotfiles in $DOTFILES..\n"

[ ! -d "$HOME/.config" ] && mkdir -v "$HOME/.config"

setup_symlink "$DOTFILES/.hushlogin" "$HOME/.hushlogin"

# zsh
setup_symlink "$DOTFILES/zsh/.zshenv" "$HOME/.zshenv"
setup_symlink "$DOTFILES/zsh/.zprofile" "$HOME/.zprofile"
setup_symlink "$DOTFILES/zsh/.zshrc" "$HOME/.zshrc"
setup_symlink "$DOTFILES/zsh/.zsh_aliases" "$HOME/.zsh_aliases"

# vim
setup_symlink "$DOTFILES/vim/.vimrc" "$HOME/.vimrc"
[ ! -d "$HOME/.vim/colors" ] && mkdir -pv "$HOME/.vim/colors"
setup_symlink "$DOTFILES/vim/colors/monokai.vim" "$HOME/.vim/colors/monokai.vim"

# ranger
setup_symlink "$DOTFILES/ranger/rc.conf" "$HOME/.config/ranger/rc.conf"

# tmux
setup_symlink "$DOTFILES/tmux/.tmux.conf" "$HOME/.tmux.conf"

# git
cp -n "$DOTFILES/git/.gitconfig" "$HOME/.gitconfig"

# Linux
setup_symlink "$DOTFILES/.inputrc" "$HOME/.inputrc"
