#!/usr/bin/env bash
#
# Set up user and terminal environment
#

echo "Installing programs.."
sudo apt-get update;
sudo apt-get install vim git apache2 ccat ranger;


echo "Creating users 'peter' and 'git'.."
# Create 'peter' user
if [ "$(id -u peter)" -gt 0 ]; then
    sudo adduser peter

    # Add 'peter' to sudo
    sudo usermod -aG sudo peter
fi
# Create 'git' user
if [ "$(id -u git)" -gt 0 ]; then
    sudo adduser git
    sudo usermod -aG www-data git
fi


# SSH
echo "Setting up SSH"
git clone git@github.com:peterlopez/dotfiles.git;
ssh-keygen -f ~/.ssh/peterlopez-github -t rsa -b 4096


echo "Configuring programs.."
cd -v /home/peter;
git clone git@github.com:peterlopez/dotfiles.git;
git clone git@github.com:peterlopez/scripts.git;
