#!/bin/bash
#
# Sync dotfiles between 
#
if [ ! -d "$DOTFILES" ]; then
  echo "\"$DOTFILES\" location not set.";
  exit 1;
fi

echo -e "Syncing dotfiles between $DESTDIR..\n";

[ -f ~/.inputrc ] && cp -v ~/.inputrc $DESTDIR;

# Aliases
[ -f ~/.aliases ] && cp -v ~/.aliases $DESTDIR;
[ -f ~/.aliases ] && cp -v ~/.aliases.macos $DESTDIR;

# Fish
[ -f ~/.config ] && cp -v ~/.config/fish/config.fish "${DESTDIR}/fish/";
[ -d ~/.config/fish/functions ] && cp -vR ~/.config/fish/functions "${DESTDIR}/fish/";

# Bash
[ -f ~/.profile ] && cp -v ~/.profile "${DESTDIR}/bash/";
[ -f ~/.bashrc ] && cp -v ~/.bashrc "${DESTDIR}/bash/";
[ -f ~/.bash_profile ] && cp -v ~/.bash_profile "${DESTDIR}/bash/";

# tmux
[ -f ~/.tmux.conf ] && cp -v ~/.tmux.conf "${DESTDIR}/tmux/";

# vim
[ -f ~/.vimrc ] && cp -v ~/.vimrc "${DESTDIR}/vim/";

# git
[ -f ~/.gitconfig ] && cp -v ~/.gitconfig "${DESTDIR}/git/";
[ -f ~/.gitignore_global ] && cp -v ~/.gitignore_global "${DESTDIR}/git/";

echo -e "\nComplete!";
