#!/bin/bash
torrentid=$1
torrentname=$2
torrentpath=$3

PLEX_SERVER_IP="10.0.69.2"
PLEX_SERVER_PATH="/media/peter/media"

if [[ $torrentpath == *"Movies"* ]]; then
	rsync -rvh "$torrentpath/$torrentname" peter@10.0.69.2:/media/peter/media/Movies;
elif [[ $torrentpath == *"TV"* ]]; then
	rsync -rvh "$torrentpath/$torrentname" peter@10.0.69.2:/media/peter/media/TV;
fi

