#!/bin/bash
#
# dockerr
# A layer on top of 'docker' program for shortcuts

help() {
    echo "Usage: dockerr command 
Commands:
    start : Start Docker for Mac app
    quit : Quit Docker for Mac app
    run php : Run php-apache container
    stop : Stop all running containers
    shutdown : Stop all and quit Mac app
    cleanup : Remove all stopped containers
    help : Show list of available commands"
}

# Start Docker app for Mac
start() {
    dockerIsRunning="$(ps aux | grep Docker.app | wc -l)"
    if [ $dockerIsRunning -gt 1 ]
    then
        echo "Docker is already running."
    else
        open -a /Users/peter/Applications/Docker.app
        echo "Docker started."
    fi 
}

# Run php-apache container
run_php() {
  echo "Starting php:7.2-apache container"
  docker run -d -p 80:80 --name "$(basename $PWD)" -v "$PWD":/var/www/html php:7.2-apache
}

# Stop all containers
# Remove all containers
# Remove all untagged images
cleanup() {
  images="$(docker images | grep '^<none>' | awk '{print $3}' | sed '/^[[:space:]]*$/d')"
  containers="$(docker ps -aq)"
  nothingtodo=1

  if [ ! -z "$containers" ]; then
    echo "Stopping all containers..";
    docker stop $containers
  
    echo -e "\nRemoving all containers..";
    docker rm $containers
    nothingtodo=0
  fi;

  if [ ! -z "$images" ]; then
    echo -e "\nRemoving untagged images..";
    docker rmi $images
    nothingtodo=0
  fi
  
  if [ $nothingtodo -gt 0 ]; then
    echo -e "\nNothing to cleanup!"
  else
    echo -e "\nDone."
  fi
}

# main
while [ "$1" != "" ]; do
    case $1 in        

        start)                  start 
                                exit
                                ;;

        # Quit Docker for Mac app
        quit | -q)              osascript -e 'quit app "Docker"'
                                exit
                                ;;

        # Start a container in this directory
        run )                   shift
                                container=$1
                                if [ "$container" = "php" ]
                                then
                                  run_php
                                fi
                                exit
                                ;;

        # Stop all running containers
        stop)                   docker stop $(docker ps -aq)
                                echo "All containers stopped."
                                exit
                                ;;

        shutdown )              docker stop "$(docker ps -a -q)"
                                osascript -e 'quit app "Docker"'
                                echo "All containers stopped. Docker for Mac quit."
                                exit
                                ;;

        cleanup )               cleanup
                                exit
                                ;;

        -h | --help )           help 
                                exit
                                ;;

        * )                     help 
                                exit 1
    esac
    shift
done

help

