#!/bin/bash
# Removes all tags from specified remote repository
if [ "$#" -lt 1 ]; then
   printf "Specify a Git remote like 'gitdeleteremotetags origin'\n\n"
   exit 0
fi
remote=$1

read -r -p "Are you sure you want to delete all tags from $remote? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
   printf "\nRemoving all tags from $remote...\n"
    git ls-remote --tags $remote | awk '/^(.*)(\s+)(.*[a-zA-Z0-9])$/ {print ":" $2}' | xargs git push $remote;
else
   printf "Exiting...\n\n"
    exit 0
fi
exit 0
